//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ВКР.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Зміст_реалізації> Зміст_реалізації { get; set; }
        public virtual DbSet<Користувачі> Користувачі { get; set; }
        public virtual DbSet<Магазини> Магазини { get; set; }
        public virtual DbSet<Матеріали> Матеріали { get; set; }
        public virtual DbSet<Реалізація> Реалізація { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
        public virtual DbSet<Товар_по_категоріям> Товар_по_категоріям { get; set; }
        public virtual DbSet<Товар_по_порам_року> Товар_по_порам_року { get; set; }
        public virtual DbSet<Товарна_група> Товарна_група { get; set; }
    }
}
